FROM python:3.8

ENV PYTHONUNBUFFERED 1
ENV DJANGO_new_SETTINGS_MODULE project.settings

WORKDIR /code

COPY requirements.txt /code/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /code/

